import type { NextPage } from "next";
import Head from "next/head";
import NavbarPrincipal from "../components/layout/NavbarPrincipal";
import FooterPrincipal from "../components/layout/FooterPrincipal";
import HeaderImg from "../components/sections/header/HeaderImg";
import HowWorks from "../components/sections/how-it-works/HowWorks";
import CarouselApp from "../components/sections/carousel-app/CarouselApp";
import WeMakeCompanies from "../components/sections/we-make-better-companies/WeMakeCompanies";
import RelevantInformation from "../components/sections/relevant-information-with-our-reports/RelevantInformation";
import IndexingInCompany from "../components/sections/indexing-in-your-company/IndexingInCompany";
import OurTeam from "../components/sections/our-team/OurTeam";
import WhatClientSays from "../components/sections/what-our-clients-says/WhatClientSays";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Diligentisa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <NavbarPrincipal />

        <section id="header">
          <HeaderImg />
        </section>

        <section id="how-works">
          <HowWorks />
        </section>

        <section id="carousel">
          <CarouselApp />
        </section>

        <section id="make-companies">
          <WeMakeCompanies />
        </section>

        <section id="relevant-information">
          <RelevantInformation />
        </section>

        <section id="indexing-companies">
          <IndexingInCompany />
        </section>

        {/* <section id="our-team">
          <OurTeam />
        </section> */}

        <section id="say-clients">
          <WhatClientSays />
        </section> 

        <FooterPrincipal />
      </main>
    </div>
  );
};

export default Home;
