import type { NextPage } from "next";
import Head from "next/head";
import NavbarPrincipal from "../components/layout/NavbarPrincipal";
import FooterPrincipal from "../components/layout/FooterPrincipal";
import HeaderImg from "../components/sections/header/HeaderImg";
import SuperpowersCircle from "../components/sections/superpowers-circle/SuperpowersCircle";
import KnowMore from "../components/sections/know-more/KnowMore";
import DidYouKnow from "../components/sections/did-you-know/DidYouKnow";
import PrivacyPolicy from "../components/sections/privacy-policy/PrivacyPolicy";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Diligentisa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <NavbarPrincipal />

        <section id="header">
          <HeaderImg />
        </section>

        <section id="header">
          <DidYouKnow />
        </section>

        <section id="relevant-information">
          <KnowMore />
        </section>

        <section id="how-works">
          <SuperpowersCircle />
        </section>

        <section id="indexing-companies">
          <PrivacyPolicy />
        </section>

        <FooterPrincipal />
      </main>
    </div>
  );
};

export default Home;
